name: Pentagon Pizza Meter

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-pentagon-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Pentagon Pizza Meter
        env:
          JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}
        run: |
          python pentagon_pizza.py
